insert into regions(name) values ('Europe')
insert into regions(name) values ('Americas')
insert into regions(name) values ('Asia')
insert into regions(name) values ('Middle East and Africa')
insert into countries(name, region_id) values ('Italy', 1)
insert into countries(name, region_id) values ('Japan', 3)
insert into countries(name, region_id) values ('USA', 2)
insert into countries(name, region_id) values ('Egypt', 4)
insert into locations(city, postal_code, street_address, country_id) values ('Roma', '00989', '1297 Via Cola di Rie', 1)
insert into locations(city, postal_code, street_address, country_id) values ('Tokyo', '1689', '2017 Shinjuku-ku', 2)
insert into locations(city, postal_code, street_address, country_id) values ('San Francisco', '26192', '2014 Jabberwocky Rd', 3)
insert into locations(city, postal_code, street_address, country_id) values ('Cairo', '54534', '46 Mohammed El Kouly', 4)